[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crud_blog_post = "FGTh7ctrHYRTTarC1SVRcbXDQP2YoQWfdLM9NP1LZGDJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
